### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by ssozonoff** [projetoarduino/goled#1]
Cant get this to work with your library but display works fine from other languages like Python.

`root@raspberrypi:/usr/local/goled/examples# ./examples
Oled Driver
2019-06-03T17:09:14.040 [     i2c] DEBUG  Write 26 hex bytes: [a6aed580a83fd300008d142000a1c8da12818fd9f1db40a4a6af]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1017f8]

goroutine 1 [running]:
github.com/d2r2/go-i2c.(*I2C).write(0x0, 0x1e0f30, 0x1a, 0x1a, 0x2, 0x2, 0x0)
	/root/go/src/github.com/d2r2/go-i2c/i2c.go:57 +0x14
github.com/d2r2/go-i2c.(*I2C).WriteBytes(0x0, 0x1e0f30, 0x1a, 0x1a, 0x1, 0x1, 0xc)
	/root/go/src/github.com/d2r2/go-i2c/i2c.go:64 +0x12c
github.com/projetoarduino/goled.(*DisplayBuffer).Init(0x12050540)
	/root/go/src/github.com/projetoarduino/goled/goled.go:73 +0x44
main.main()
	/usr/local/goled/examples/main.go:14 +0x54`

**Comment by adrianh-za** [comment]
I had same problem, solved by making a single code change.

Open the **goled.go** file and change line 70 from 

`var conn, _ = i2c.NewI2C(OLED_ADDR, 0)`

to

`var conn, _ = i2c.NewI2C(OLED_ADDR, 1)`

and the example will work correctly.
